# Generated by Django 2.2.1 on 2019-05-22 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Of_Account',
            fields=[
                ('field_id', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('field_account', models.CharField(max_length=100)),
                ('field_account_libaccount', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('field_subtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('company_name', models.TextField()),
                ('fiscal_end_of_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_subgroup',
            fields=[
                ('field_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('groupparent_id', models.BigIntegerField()),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_firstname', models.TextField()),
                ('user_lastname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Varification_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.BigIntegerField()),
                ('field_account', models.CharField(max_length=100)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('fiscal_year', models.DateField()),
                ('month', models.IntegerField()),
                ('upload_version', models.IntegerField()),
            ],
        ),
    ]
