# Generated by Django 2.2.1 on 2019-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varification_balance',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='varification_balance',
            name='currency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_firstname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.TextField(null=True),
        ),
    ]
