# Generated by Django 2.2.1 on 2019-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_auto_20190523_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='fiscal_year',
            field=models.IntegerField(),
        ),
    ]
