# Generated by Django 2.2.1 on 2019-05-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_varification_balance_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='upload_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
