# Generated by Django 2.2.1 on 2019-05-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0010_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
