# Generated by Django 2.2.1 on 2019-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0012_auto_20190524_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='upload_file',
            field=models.FileField(default='', null=True, upload_to='DataStoreApp/StoreApp/static/media'),
        ),
    ]
