# Generated by Django 2.2.1 on 2019-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0013_auto_20190524_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='upload_file',
            field=models.FileField(default='', null=True, upload_to='media'),
        ),
    ]
