# Generated by Django 2.2.1 on 2019-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0014_auto_20190524_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_subgroup',
            name='field_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
