# Generated by Django 2.2.1 on 2019-05-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0015_auto_20190529_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_subgroup',
            name='groupparent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.Group_subgroup'),
        ),
    ]
