# Generated by Django 2.2.1 on 2019-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0018_varification_balance_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='varification_balance',
            name='field_account',
            field=models.CharField(max_length=200),
        ),
    ]
