# Generated by Django 2.2.1 on 2019-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0019_auto_20190604_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
