# Generated by Django 2.2.1 on 2019-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0020_auto_20190604_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='varification_balance',
            name='credit',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='varification_balance',
            name='debit',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='varification_balance',
            name='month',
            field=models.IntegerField(default=170),
        ),
    ]
