# Generated by Django 2.2.1 on 2019-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0021_auto_20190604_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varification_balance',
            name='fiscal_year',
            field=models.IntegerField(default=170),
        ),
    ]
