# Generated by Django 2.2.1 on 2019-06-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0023_auto_20190604_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('subgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('subgroup_name', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Group_subgroup',
        ),
    ]
