# Generated by Django 2.2.1 on 2019-06-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0024_auto_20190607_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varification_balance',
            name='company',
        ),
    ]
