# Generated by Django 2.2.1 on 2019-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0025_remove_varification_balance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='varification_balance',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
