# Generated by Django 2.2.1 on 2019-06-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0026_varification_balance_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart_Of_Account',
        ),
    ]
