# Generated by Django 2.2.1 on 2019-06-08 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0027_delete_chart_of_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Of_Account',
            fields=[
                ('no_compte', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('field_account', models.CharField(max_length=100)),
                ('field_account_libaccount', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('field_subtype', models.CharField(max_length=100)),
            ],
        ),
    ]
