# Generated by Django 2.2.1 on 2019-06-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0028_chart_of_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varification_balance',
            name='company',
        ),
    ]
