# Generated by Django 2.2.1 on 2019-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0031_chart_of_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='varification_balance',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
